services:
  diary:
    profiles: ["heartmeter"]
    container_name: heartmeter.diary
    hostname: heartmeter.diary
    build:
      context: .
      dockerfile: diary/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
      rabbit:
        condition: service_healthy
    networks:
      - heartmeter.postgres.network
      - heartmeter.diary.network
      - heartmeter.rabbit.network
    env_file:
      - ./diary/.env.docker

  reporter:
    profiles: ["heartmeter"]
    container_name: heartmeter.reporter
    hostname: heartmeter.reporter
    build:
      context: .
      dockerfile: reporter/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      rabbit:
        condition: service_healthy
      weather:
        condition: service_started
    networks:
      - heartmeter.rabbit.network
      - heartmeter.weather.network
    env_file:
      - ./reporter/.env.docker
    volumes:
      - ./reports:/app/reports:rw

  weather:
    profiles: ["heartmeter"]
    container_name: heartmeter.weather
    hostname: heartmeter.weather
    build:
      context: .
      dockerfile: weather/Dockerfile
    restart: unless-stopped
    ports:
      - "8082:8082"
    networks:
      - heartmeter.weather.network
    env_file:
      - ./weather/.env.docker

  migration:
    profiles: ["heartmeter", "migration"]
    container_name: heartmeter.migration
    build:
      context: .
      dockerfile: diary/Dockerfile
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - heartmeter.postgres.network
    env_file:
      - ./diary/.env.docker
    volumes:
      - ./diary/alembic.ini:/app/alembic.ini:ro
    command: ["python", "-m", "alembic", "upgrade", "head"]

  postgres:
    profiles: ["heartmeter", "migration"]
    container_name: heartmeter.postgres
    image: "postgres:15-alpine"
    hostname: heartmeter.postgres
    restart: unless-stopped
    ports:
      - "15432:5432"
    networks:
      - heartmeter.postgres.network
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C --lc-ctype=C"
      POSTGRES_SHARED_BUFFERS: 1GB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 3GB
      POSTGRES_WORK_MEM: 400MB
      POSTGRES_MAINTENANCE_WORK_MEM: 1GB
      POSTGRES_CHECKPOINT_COMPLETION_TARGET: 0.9
      POSTGRES_MAX_WAL_SIZE: 2GB
      POSTGRES_WAL_BUFFERS: 8MB
      POSTGRES_RANDOM_PAGE_COST: 1.1
      POSTGRES_EFFECTIVE_IO_CONCURRENCY: 4
    volumes:
      - heartmeter.postgres.data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s

  rabbit:
    profiles: ["heartmeter"]
    image: rabbitmq:3.11-management-alpine
    container_name: heartmeter.rabbit
    hostname: heartmeter.rabbit
    restart: unless-stopped
    ports:
      - "5671:5671"
      - "5672:5672"
      - "15672:15672"
    networks:
      - heartmeter.rabbit.network
    volumes:
      - heartmeter.rabbit.data:/var/lib/rabbitmq/:rw
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD:-admin}
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics check_running -q" ]
      interval: 10s
      timeout: 60s
      retries: 5
      start_period: 10s
      
  grafana:
    profiles: ["observability"]
    image: grafana/grafana:latest
    container_name: heartmeter.grafana
    hostname: heartmeter.grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - heartmeter.observability.network
    volumes:
      - heartmeter.grafana.data:/var/lib/grafana:rw
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:rw
      - ./monitoring/grafana/dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DATABASE_WAL=true
      - VIRTUAL_HOST=heartmeter.grafana
      - NETWORK_ACCESS=internal
      - VIRTUAL_PORT=3000

  loki:
    profiles: ["observability"]
    image: grafana/loki:2.9.6
    container_name: heartmeter.loki
    hostname: heartmeter.loki
    expose:
      - "3100"
    volumes:
      - ./monitoring/loki/config.yaml:/etc/loki/config.yaml:ro
      - heartmeter.loki.data:/tmp/:rw
    command: -config.file=/etc/loki/config.yaml
    restart: unless-stopped
    networks:
      - heartmeter.observability.network

  vector:
    profiles: ["observability"]
    image: timberio/vector:0.42.0-alpine
    container_name: heartmeter.vector
    hostname: heartmeter.vector
    restart: unless-stopped
    command: --config=/etc/vector/vector.toml
    networks:
      - heartmeter.observability.network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./monitoring/vector/vector.toml:/etc/vector/vector.toml:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

  prometheus:
    profiles: ["observability"]
    image: prom/prometheus:latest
    container_name: heartmeter.prometheus
    hostname: heartmeter.prometheus
    restart: unless-stopped
    networks:
      - heartmeter.observability.network
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - heartmeter.prometheus.data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"

  cadvisor:
    profiles: ["observability"]
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: heartmeter.cadvisor
    hostname: heartmeter.cadvisor
    restart: unless-stopped
    networks:
      - heartmeter.observability.network
    ports:
      - "8083:8083"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    command:
      - "-port=8083"
    privileged: true

volumes:
  heartmeter.postgres.data: {}
  heartmeter.rabbit.data: {}
  heartmeter.loki.data: {}
  heartmeter.grafana.data: {}
  heartmeter.prometheus.data: {}

networks:
  heartmeter.diary.network: {}
  heartmeter.weather.network: {}
  heartmeter.postgres.network: {}
  heartmeter.rabbit.network: {}
  heartmeter.observability.network: {}
