[sources.docker]
type = "docker_logs"
docker_host = "/var/run/docker.sock"
include_containers = [
    "heartmeter.diary",
    "heartmeter.reporter",
    "heartmeter.weather",
]

[transforms.json]
type = "remap"
inputs = ["docker"]
drop_on_error = true
source = ".message = object!(parse_json(.message) ?? {})"

[sinks.loki_sync_id]
type = "loki"
inputs = ["json"]
encoding.codec = "json"
labels.level = "{{ message.level }}"
labels.container_name = "{{ container_name }}"
endpoint = "http://heartmeter.loki:3100"
