{
 "title": "Logs",
 "tags": [ "logs" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "container_name",
    "label": "Container Name",
    "query": {}
   },
   {
    "name": "log_level",
    "label": "Log Level",
    "query": "error, warning, info, debug, critical"
   },
   { "name": "log_keyword", "label": "Log Keyword" }
  ]
 },
 "panels": [
  {
   "title": "Total errors by interval",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container_name=~\"$container_name\", level=\"error\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Log type rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (rate({container_name=~\"$container_name\", level=~\"$log_level\"} |= \"$log_keyword\" [1m]))",
     "legendFormat": "{{.message_level}}"
    }
   ]
  },
  {
   "title": "Total warnings by interval",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({container_name=~\"$container_name\", level=\"warning\"} [$__range]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 24, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container_name=~\"$container_name\", level=~\"$log_level\"} |= \"$log_keyword\" | json | line_format \"{{.container_name}}\\t{{.message_timestamp}}\\t{{.message_level}}\\t\\t{{.message_event}} {{if .message_trace_id}}\\t trace_id={{.message_trace_id}}{{end}}\""
    }
   ]
  }
 ]
}