set dotenv-load := true

# Show help message
[private]
@default:
    just --list

# Install all depends for developing
@install:
    uv pip install -e .

# Lint
@lint:
    ruff check --config  ./pyproject.toml --fix
    ruff format --config  ./pyproject.toml
    mypy src --config-file ./pyproject.toml

# Run
@run:
    python3 -m weather.main
