[db]
host = "127.0.0.1"
port = 5432
database = "postgres"
user = "postgres"
password = "postgres"
max_idle_connection = 100

[api]
host = "127.0.0.1"
port = 8080
request_timeout = "4s"
idle_timeout = "60s"
base_url_prefix = "/api/v1"

[logging]
level = "info"
render_json = false
