db_url := env_var_or_default("DB_URL", "")

# Show help message
[private]
@default:
    just --list

# Install all depends
@install:
    go mod download
    go install github.com/pressly/goose/v3/cmd/goose@latest

# Run server
@run:
    go run cmd/http/main.go

# Up migrations
@upgrade:
    goose -dir migrations postgres {{ db_url }} up

# Down migrations
@downgrade:
    goose -dir migrations postgres {{ db_url }} down
