apiVersion: 1

datasources:
  - uid: loki
    orgId: 1
    name: Loki
    type: loki
    access: proxy
    url: http://heartmeter.loki:3100
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: $${__value.raw}
      timeInterval: 15s
