apiVersion: 1

datasources:
  - uid: "loki"
    orgId: 1
    name: "Loki"
    type: "loki"
    access: "proxy"
    url: "http://heartmeter.loki:3100"
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: $${__value.raw}
      timeInterval: "15s"
  - uid: "prometheus"
    name: "Prometheus"
    orgId: 1
    type: "prometheus"
    typeName: "Prometheus"
    access: "proxy"
    url: "http://heartmeter.prometheus:9090"
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    readOnly: false
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: "tempo"
          name: "TraceID"
      httpMethod: "POST"
  - uid: "tempo"
    orgId: 1
    name: "Tempo"
    type: "tempo"
    typeName: "Tempo"
    access: "proxy"
    url: "http://heartmeter.tempo:3200"
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: false
    jsonData:
      httpMethod: "GET"
      serviceMap:
        datasourceUid: "prometheus"
      nodeGraph:
        enabled: true
      search:
        hide: false
      lokiSearch:
        datasourceUid: "loki"
      tracesToLogsV2:
        datasourceUid: "loki"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{container_name=~".+"} | json | message_trace_id="$${__span.traceId}" and message_span_id="$${__span.spanId}" | line_format "{{.container_name}}\t{{.message_timestamp}}\t{{.message_level}}\t\t{{.message_event}}"'
    readOnly: false
    editable: true
