apiVersion: 1

datasources:
  - uid: "loki"
    orgId: 1
    name: "Loki"
    type: "loki"
    access: "proxy"
    url: "http://heartmeter.loki:3100"
    basicAuth: false
    isDefault: false
    editable: true
    version: 1
    jsonData:
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: "trace_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"
      timeInterval: "15s"
  - uid: "prometheus"
    name: "Prometheus"
    orgId: 1
    type: "prometheus"
    typeName: "Prometheus"
    access: "proxy"
    url: "http://heartmeter.prometheus:9090"
    password: ""
    user: ""
    database: ""
    basicAuth: false
    isDefault: true
    readOnly: false
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: "tempo"
          name: "TraceID"
      httpMethod: "POST"
