db:
  type: postgresql
  host: 127.0.0.1
  port: 5432
  name: postgres
  user: postgres
  password: postgres
http:
  host: 127.0.0.1
  port: 8080
  request_timeout: 4s
  idle_timeout: 60s
log:
  level: INFO
  render_json: false
